#!/bin/bash

cat \
	TITLE.md \
	INTRODUCTION.md \
	MARKET_ANALYSIS.md \
	POSSIBLE_APPROACH_ANALYSIS.md \
	MARKET_ENTRY_PLAN.md \
	OPEN_SOURCE_SIMULATORS_COMPARISON.md \
	GOALS_AND_RATIONALE.md \
	POC_DEVELOPMENT_PATH.md \
	ACHIEVEMENTS_TO_DATE.md \
	EXAMPLES_AND_EVALUATION.md \
	LIMITATIONS_AND_CHALLENGES.md \
	NEXT_STAGES_AND_FUTURE_WORK.md \
	CONCLUSION.md \
>../PROJECT_PRESENTATION_COMBINED.md

