// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vedge_detector_test.cpp"
#include "Vedge_detector_test___024root__DepSet_h61a3efc4__0.cpp"
#include "Vedge_detector_test___024root__DepSet_h5f5a6e71__0.cpp"
#include "Vedge_detector_test__main.cpp"
#include "Vedge_detector_test__Trace__0.cpp"
#include "Vedge_detector_test___024root__Slow.cpp"
#include "Vedge_detector_test___024root__DepSet_h5f5a6e71__0__Slow.cpp"
#include "Vedge_detector_test__Syms.cpp"
#include "Vedge_detector_test__Trace__0__Slow.cpp"
#include "Vedge_detector_test__TraceDecls__0__Slow.cpp"
